### ISSUE TITLE
quincunx

### ISSUE THREAD

**Issue by adeldaoud** [yihui/animation#119]
Hi

Just installed `animation `and ran the `quincunx `function. But getting the following error:

```
> quincunx(balls = 10, layers = 15, pch.layers = 2, pch.balls = 19, 
+          col.balls = sample(colors(), balls, TRUE), cex.balls = 2)

Error in sample.int(length(x), size, replace, prob) : 
  object 'balls' not found
In addition: Warning message:
In quincunx(balls = 10, layers = 15, pch.layers = 2, pch.balls = 19,  :
  It's strongly recommended that ani.options(nmax = balls + layers -2)
```

**Comment by yulijia** [comment]
In you code, there is a variable called `balls` at line 2 ( `col.balls=sample(colors(),balls,TRUE)`, you need set a number to this variable.

**Comment by adeldaoud** [comment]
Thanks! That helped. I assumed it was set already by the first argument.
