### ISSUE TITLE
Problem with ``saveGIF`` on Windows

### ISSUE THREAD

**Issue by kendonB** [yihui/animation#67]
I'm getting the following error when I run the example from the help file:

    saveGIF({
      for (i in 1:10) plot(runif(10), ylim = 0:1)
    })

    I cannot find ImageMagick with convert = "convert"
    but I can find it from the "Program Files" directory: C:\Program Files/ImageMagick-6.9.1-Q16/convert.exe
    Executing: 
      "C:\Program Files\ImageMagick-6.9.1-Q16\convert.exe" -loop 0 -delay 100 Rplot1.png Rplot2.png Rplot3.png
    Rplot4.png Rplot5.png Rplot6.png Rplot7.png Rplot8.png Rplot9.png Rplot10.png "animation.gif"
    'C:\Program' is not recognized as an internal or external command,
    operable program or batch file.
    convert.exe: unable to load module `C:\Program Files\ImageMagick-6.9.1-Q16\modules\coders\IM_MOD_RL_PNG_.dll': The specified module could not be found.
    @ error/module.c/OpenModule/1282.
    convert.exe: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/501.
    convert.exe: unable to load module `C:\Program Files\ImageMagick-6.9.1-Q16\modules\coders\IM_MOD_RL_PNG_.dll': The specified module could not be found.
    @ error/module.c/OpenModule/1282.
    convert.exe: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/501.
    convert.exe: unable to load module `C:\Program Files\ImageMagick-6.9.1-Q16\modules\coders\IM_MOD_RL_PNG_.dll': The specified module could not be found.
    @ error/module.c/OpenModule/1282.
    convert.exe: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/501.
    convert.exe: unable to load module `C:\Program Files\ImageMagick-6.9.1-Q16\modules\coders\IM_MOD_RL_PNG_.dll': The specified module could not be found.
    @ error/module.c/OpenModule/1282.
    convert.exe: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/501.
    convert.exe: unable to load module `C:\Program Files\ImageMagick-6.9.1-Q16\modules\coders\IM_MOD_RL_PNG_.dll': The specified module could not be found.
    @ error/module.c/OpenModule/1282.
    convert.exe: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/501.
    convert.exe: unable to load module `C:\Program Files\ImageMagick-6.9.1-Q16\modules\coders\IM_MOD_RL_PNG_.dll': The specified module could not be found.
    @ error/module.c/OpenModule/1282.
    convert.exe: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/501.
    convert.exe: unable to load module `C:\Program Files\ImageMagick-6.9.1-Q16\modules\coders\IM_MOD_RL_PNG_.dll': The specified module could not be found.
    @ error/module.c/OpenModule/1282.
    convert.exe: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/501.
    convert.exe: unable to load module `C:\Program Files\ImageMagick-6.9.1-Q16\modules\coders\IM_MOD_RL_PNG_.dll': The specified module could not be found.
    @ error/module.c/OpenModule/1282.
    convert.exe: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/501.
    convert.exe: unable to load module `C:\Program Files\ImageMagick-6.9.1-Q16\modules\coders\IM_MOD_RL_PNG_.dll': The specified module could not be found.
    @ error/module.c/OpenModule/1282.
    convert.exe: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/501.
    convert.exe: unable to load module `C:\Program Files\ImageMagick-6.9.1-Q16\modules\coders\IM_MOD_RL_PNG_.dll': The specified module could not be found.
    @ error/module.c/OpenModule/1282.
    convert.exe: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/501.
    convert.exe: no images defined `animation.gif' @ error/convert.c/ConvertImageCommand/3230.
    an error occurred in the conversion... see Notes in ?im.convert
    [1] FALSE
    Warning messages:
    1: running command 'C:\Windows\system32\cmd.exe /c convert --version' had status 4 
    2: running command 'C:\Windows\system32\cmd.exe /c "C:\Program Files\ImageMagick-6.9.1-Q16\convert.exe" -loop 0  -delay 100 Rplot1.png Rplot2.png Rplot3.png Rplot4.png Rplot5.png Rplot6.png Rplot7.png Rplot8.png Rplot9.png Rplot10.png "animation.gif"' had status 1 
    3: In cmd.fun(convert) :
    '"C:\Program Files\ImageMagick-6.9.1-Q16\convert.exe" -loop 0  -delay 100 Rplot1.png Rplot2.png Rplot3.png Rplot4.png Rplot5.png Rplot6.png Rplot7.png Rplot8.png Rplot9.png Rplot10.png "animation.gif"' execution failed with error code 1
    4: running command '"C:\Program Files\ImageMagick-6.9.1-Q16\convert.exe" -loop 0  -delay 100 Rplot1.png Rplot2.png Rplot3.png Rplot4.png Rplot5.png Rplot6.png Rplot7.png Rplot8.png Rplot9.png Rplot10.png "animation.gif"' had status 1 
    5: In normalizePath(path.expand(path), winslash, mustWork) :
    path[1]="animation.gif": The system cannot find the file specified
Looks like it's not escaping the space in "Program Files" and also not locating the "IM_MOD_RL_PNG_.dll" file.

**Comment by yulijia** [comment]
Hi Kendon,

I installed ImageMagick-6.9.1-Q16  on a Windows 7  OS, and ran the same example as yours.
However I didn't  reproduce your bug successfully. 

Would your mind to tell me the animation package version you have used? And any other details to reproduce the bug?

For me, I use the stable version 2.3, install ImageMagick-6.9.1-Q16 to the default directory.

BTW,
>'C:\Program' is not recognized as an internal or external command, operable program or batch file.
The above line is a warning message, it doesn't bring the error.

**Comment by kendonB** [comment]
I am running: 
Windows Server 2008 R2 Enterprise, Service Pack 1
RRO 3.2.0
animation 2.3
ImageMagick-6.9.1-Q16

. After a logout/login and restart of RStudio / R, this errors are now:

    library(animation) # ver 2.3
    saveGIF({
         for (i in 1:10) plot(runif(10), ylim = 0:1)
    })
    Executing: 
      "convert" -loop 0 -delay 100 Rplot1.png Rplot2.png Rplot3.png Rplot4.png Rplot5.png Rplot6.png Rplot7.png
    Rplot8.png Rplot9.png Rplot10.png "animation.gif"
    'convert" -loop 0  -delay 100 Rplot1.png Rplot2.png Rplot3.png Rplot4.png Rplot5.png Rplot6.png Rplot7.png Rplot8.png Rplot9.png Rplot10.png "animation.gif' is not recognized as an internal or external command,
    operable program or batch file.
    Invalid Parameter - 0
    an error occurred in the conversion... see Notes in ?im.convert
    [1] FALSE
    Warning messages:
    1: running command 'C:\Windows\system32\cmd.exe /c "convert" -loop 0  -delay 100 Rplot1.png Rplot2.png Rplot3.png Rplot4.png Rplot5.png Rplot6.png Rplot7.png Rplot8.png Rplot9.png Rplot10.png "animation.gif"' had status 1 
    2: In cmd.fun(convert) :
      '"convert" -loop 0  -delay 100 Rplot1.png Rplot2.png Rplot3.png Rplot4.png Rplot5.png Rplot6.png Rplot7.png Rplot8.png Rplot9.png Rplot10.png "animation.gif"' execution failed with error code 1
    3: running command '"convert" -loop 0  -delay 100 Rplot1.png Rplot2.png Rplot3.png Rplot4.png Rplot5.png Rplot6.png Rplot7.png Rplot8.png Rplot9.png Rplot10.png "animation.gif"' had status 4 
    4: In normalizePath(path.expand(path), winslash, mustWork) :
      path[1]="animation.gif": The system cannot find the file specified

**Comment by yulijia** [comment]
Thank you.

I can reproduce the problem now. It seems RRO can not find the convert.exe .

I am not familiar with Windows system and RRO, it may take a few days to fix the bug. If you need using `saveGIF()` function immediately, please try install **R for windows** , it  can be downloaded from the [**r-project** website](http://www.r-project.org/).

**Comment by deschen2** [comment]
I have the very same problems as kendonB, not sure if it has sth. to do with 64bit vs. 32bit versions of ImageMagick? I'm running on a Win64bit system (windows 7) and thus installed ImageMagick to C:/Program Files/....

Also: when I'm running RStudio as Admin, I get the error message/problem in kendonBs FIRST post. If I'm running Rstudio not in Admin Mode I get kendonBs message from his SECOND post.

Hope that helps.

**Comment by yulijia** [comment]
Hi, deschen2

Thanks for your report. I wan to know which R software you have used? 
Revolution R Open (RRO) or the default R software.

**Comment by deschen2** [comment]
Hi Im running R version 3.2.0 (2015-04-16), but via the GUI RStudio Version 0.98.1103

**Comment by jshane** [comment]
Also having the same error described here. "C:/Program Files/ImageMagick-6.9.1-Q16" is set in my Path environment variables list.

Windows 8.1
platform   x86_64-w64-mingw32 
R version 3.2.0 (2015-04-16)
RStudio 0.99.447
animation 2.3

> library(animation)
> ani.options(convert ="C:/Program Files/ImageMagick-6.9.1-Q16/convert.exe")
> saveGIF({
+     for (i in 1:10) plot(runif(10), ylim = 0:1)
+ })
Executing: 
"C:/Program Files/ImageMagick-6.9.1-Q16/convert.exe" -loop 0 -delay 100 Rplot1.png Rplot2.png Rplot3.png Rplot4.png
    Rplot5.png Rplot6.png Rplot7.png Rplot8.png Rplot9.png Rplot10.png "animation.gif"
'C:/Program' is not recognized as an internal or external command,
operable program or batch file.
convert.exe: unable to load module `C:\Program Files\ImageMagick-6.9.1-Q16\modules\coders\IM_MOD_RL_PNG_.dll': The specified module could not be found.
 @ error/module.c/OpenModule/1282.
convert.exe: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/501.
convert.exe: unable to load module `C:\Program Files\ImageMagick-6.9.1-Q16\modules\coders\IM_MOD_RL_PNG_.dll': The specified module could not be found.
 @ error/module.c/OpenModule/1282.
convert.exe: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/501.
convert.exe: unable to load module `C:\Program Files\ImageMagick-6.9.1-Q16\modules\coders\IM_MOD_RL_PNG_.dll': The specified module could not be found.
 @ error/module.c/OpenModule/1282.
convert.exe: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/501.
convert.exe: unable to load module `C:\Program Files\ImageMagick-6.9.1-Q16\modules\coders\IM_MOD_RL_PNG_.dll': The specified module could not be found.
 @ error/module.c/OpenModule/1282.
convert.exe: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/501.
convert.exe: unable to load module `C:\Program Files\ImageMagick-6.9.1-Q16\modules\coders\IM_MOD_RL_PNG_.dll': The specified module could not be found.
 @ error/module.c/OpenModule/1282.
convert.exe: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/501.
convert.exe: unable to load module `C:\Program Files\ImageMagick-6.9.1-Q16\modules\coders\IM_MOD_RL_PNG_.dll': The specified module could not be found.
 @ error/module.c/OpenModule/1282.
convert.exe: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/501.
convert.exe: unable to load module `C:\Program Files\ImageMagick-6.9.1-Q16\modules\coders\IM_MOD_RL_PNG_.dll': The specified module could not be found.
 @ error/module.c/OpenModule/1282.
convert.exe: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/501.
convert.exe: unable to load module `C:\Program Files\ImageMagick-6.9.1-Q16\modules\coders\IM_MOD_RL_PNG_.dll': The specified module could not be found.
 @ error/module.c/OpenModule/1282.
convert.exe: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/501.
convert.exe: unable to load module `C:\Program Files\ImageMagick-6.9.1-Q16\modules\coders\IM_MOD_RL_PNG_.dll': The specified module could not be found.
 @ error/module.c/OpenModule/1282.
convert.exe: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/501.
convert.exe: unable to load module `C:\Program Files\ImageMagick-6.9.1-Q16\modules\coders\IM_MOD_RL_PNG_.dll': The specified module could not be found.
 @ error/module.c/OpenModule/1282.
convert.exe: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/501.
convert.exe: no images defined `animation.gif' @ error/convert.c/ConvertImageCommand/3230.
an error occurred in the conversion... see Notes in ?im.convert
[1] FALSE
Warning messages:
1: running command 'C:\WINDOWS\system32\cmd.exe /c "C:/Program Files/ImageMagick-6.9.1-Q16/convert.exe" -loop 0  -delay 100 Rplot1.png Rplot2.png Rplot3.png Rplot4.png Rplot5.png Rplot6.png Rplot7.png Rplot8.png Rplot9.png Rplot10.png "animation.gif"' had status 1 
2: In cmd.fun(convert) :
  '"C:/Program Files/ImageMagick-6.9.1-Q16/convert.exe" -loop 0  -delay 100 Rplot1.png Rplot2.png Rplot3.png Rplot4.png Rplot5.png Rplot6.png Rplot7.png Rplot8.png Rplot9.png Rplot10.png "animation.gif"' execution failed with error code 1
3: running command '"C:/Program Files/ImageMagick-6.9.1-Q16/convert.exe" -loop 0  -delay 100 Rplot1.png Rplot2.png Rplot3.png Rplot4.png Rplot5.png Rplot6.png Rplot7.png Rplot8.png Rplot9.png Rplot10.png "animation.gif"' had status 1 
4: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="animation.gif": The system cannot find the file specified

**Comment by robozor** [comment]
R Studio - you must run as administrator
R - it is OK
(Win 7, 64bit)

**Comment by jshane** [comment]
Running RStudio as an admin fixed this issue, thanks robozor!

**Comment by deschen2** [comment]
Running as admin indead helps. However, I always run RStudio as Admin and it didn't work before.
My feeling is that one HAS TO add the following command to get things running:

> ani.options(convert ="C:/Program Files/ImageMagick-6.9.1-Q16/convert.exe")

**Comment by sebasv** [comment]
I ran into the same problem; numerous errors of the 
```
convert.exe: unable to load module `C:\Program Files\ImageMagick-6.9.1-Q16\modules\coders\IM_MOD_RL_PNG_.dll': The specified module could not be found.
 @ error/module.c/OpenModule/1282.
```
variety, on an RStudio 0.99 / R 3.2.2 / Win10 home x64 config with ImageMagick 1.3.21 Q16 x64 installed. Restarting RStudio solved my problem, admin mode was not necessary, nor did I have to specify the absolute path to `convert.exe`. I hope this helps with the debugging. 

At any rate, thanks for a great package!

**Comment by yihui** [comment]
@sebasv Thanks for the info!

**Comment by dandermotj** [comment]
I ran into the same problem as the original poster. Either setting ani.options(convert = ".../convert.exe) explicitly or restarting RStudio solved the problem (I'm not sure which!). Thanks for the great package!

**Comment by yulijia** [comment]
Dear all,

Recently, we fix a bug of `im.convert` function, you can check issue #71 .
I tested the new `im.convert` function on my laptop( Windows Vista with Revolution R). It seems that `saveGIF()` function works well after updating to the development version animation package.
Would anyone can help me to test if you can save GIF successfully with the development version?

Here are some testing code.
```{r}
install.packages("devtools")
library(devtools)

dev_mode(on=T)

install.packages('animation', repos = 'http://yihui.name/xran')
library(animation)
saveGIF({
    for (i in 1:10) plot(runif(10), ylim = 0:1)
})

dev_mode(on=F)
```

Thanks.

Best,
Lijia

**Comment by sebasv** [comment]
I've run the test code, did not receive any errors.

**Comment by yulijia** [comment]
@sebasv Thanks for your testing and feedback!

**Comment by mnickie** [comment]
Running in R Studio (as Administrator) resolves this issue for me. Thank you @robozor !!!

**Comment by liujialu512** [comment]
Hi everyone,

I have the same problem here. When I ran Lijia's test code, I got the following:

```
sh: convert: command not found
Error in cmd.fun(sprintf("%s --version", convert), intern = TRUE) : 
  error in running command
I cannot find ImageMagick with convert = 'convert'
[1] FALSE
Warning message:
In im.convert(img.files, output = path.expand(movie.name), convert = convert,  :
  Please install ImageMagick first or put its bin path into the system PATH variable
```

I saw some of you mentioned to run in R studio (1.1.4) as administrator  (@robozor @yulijia @sebasv) . I am not very good with computers :( Can anyone be a little more specific how I can run R studio as administrator in Mac? 

Thank you so much!

Jialu

**Comment by yulijia** [comment]
@liujialu512 

Please install ImageMagick, [https://www.imagemagick.org/script/download.php](https://www.imagemagick.org/script/download.php)

 ```
brew install imagemagick
```

**Comment by liujialu512** [comment]
Thank you @yulijia! For some reason, I cannot install and use brew or macport, so I just followed their instructions and manually downloaded imagemagick. 
I was okay of doing the following:
```
cd $HOME
tar xvzf ImageMagick--x86_64-apple-darwin17.2.0.tar.gz
export MAGICK_HOME="$HOME/ImageMagick-7.0.7"
export PATH="$MAGICK_HOME/bin:$PATH"
export DYLD_LIBRARY_PATH="$MAGICK_HOME/lib/"
```
Then in the testing part, I encountered no problems with 
```
magick logo: logo.gif
identify logo.gif
```
But got error message for 
`display logo.gif`
It says I need X11 server. Then I installed XQuartz, and did 
`export DISPLAY=:0`

Going back to the R testing code (Lijia's), I still got the same error message about needing to install ImageMagick first. 

I am so sorry that I am very slow about computer stuff, but could any one of you provide some insights on what I should do?

Thanks a lot!

Jialu

**Comment by yulijia** [comment]
@liujialu512 

1. Please ensure you can use magick in Mac terminal, set up environment variable in `.bash_profile`.

2. Use `which magick` or `which convert` to find the software path, for example `/usr/local/bin/magick`

3. Set up the `convert` in `ani.options`, before run `saveGIF()`

```
ani.options(convert = '/usr/local/bin/magick'); 
```
