### ISSUE TITLE
prevent file opening

### ISSUE THREAD

**Issue by stla** [yihui/animation#69]
Hello,
When I create an animation with `saveGIF`, the output file is automatically opened. Is there a way to prevent that ?

**Comment by yulijia** [comment]
Hi,

try this

```r
ani.options(autobrowse=FALSE)
saveGIF({
for (i in 1:10) plot(runif(10), ylim = 0:1)
 })
```

 `ani.options()` function provide various parameters that control the behaviour of the animation

For example,

>autobrowse
>logical: whether auto-browse the animation page immediately after it is created? (default to be interactive())

>autoplay
>logical: whether to autoplay the animation when the HTML page is loaded (default to be TRUE); only applicable to saveHTML

**Comment by stla** [comment]
Yes, it works ! Thank you, I missed it in the help, sorry for that.
