### ISSUE TITLE
website live examples link broken

### ISSUE THREAD

**Issue by grahamjeffries** [yihui/animation#81]
[This one](http://vis.supstat.com/categories.html#animation-ref) from the [package site](http://yihui.name/animation/)

I couldn't find an obvious successor to offer...

**Comment by yulijia** [comment]
Thanks for the report. You can try use this:  http://yulijia.net/vistat/categories.html#animation-ref 
We will fix it ASAP.

supstat/vistat#14

**Comment by yulijia** [comment]
Fixed.   http://vis.supstat.com
