### ISSUE TITLE
saveGIF not working on windows (magick.exe instead of convert.exe?)

### ISSUE THREAD

**Issue by JeromeMathieuEcology** [yihui/animation#86]
Hi Yihui,

I can't make work saveGIF on windows. I get the following message:

1: running command 'C:\Windows\system32\cmd.exe /c convert --version' had status 4 
2: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:\Program Files\ImageMagick-7.0.3-Q16/convert.exe": file cannot be found

I checked my computer's path and  Magick Documentation and found that in the last version of Magick (7.0.3-5 Q16 x64 2016-11-08), the function "convert" is now named "magick" on windows OS.

So I tried " convert = "magick" " in the call of saveGIF but it didn't work:

Error in match.arg(convert) : 
  'arg' should be one of “convert”, “gm convert”

And I can't find where to modify the function saveGIF to make it work.

Any clue how to fix this?
Thank you,
Jerome

**Comment by yulijia** [comment]
Hi @JeromeMathieuEcology, Thanks for your feedback,  we will fix it as soon as possible.

You can try reinstall `ImageMagick-7.0.3-Q16` with `convert`, following the discussion #55

**Comment by JeromeMathieuEcology** [comment]
Hi Yihui,

Re installing ImageMagick with the  "legacy" utilities, as you suggested, did the job.
[http://www.imagemagick.org/discourse-server/viewtopic.php?t=29761](url)

Thank a lot for your help (and for your package!)/
Jerome
